apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: dgvigil/scratch-test:v1
    name: test-container-01
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: dgvigil/scratch-test:v1
    name: test-container-02
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  initContainers:
  - name: init-test
    image: dgvigil/scratch-test:init
    command: ['sh', '-c', "echo this is a test | tee /tmp/test-file"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
